### ISSUE TITLE
Simplify Example 1

### ISSUE THREAD

**Issue by CHBresser** [gudnm/codekatas#1]
I know this is being kinda pedantic but you can simplify Example 1 greatly. 
Your code:
```
def palindrome(string):
    """Check if input string (all lower-case characters) is a palindrome."""
    for i in range(len(string)//2):
        if string[i] != string[len(string)-i-1]:
            return False
    return True
    
assert palindrome('') == True
assert palindrome('a') == True
assert palindrome('ab') == False
assert palindrome('abba') == True
assert palindrome('redivider') == True
print('All passed!')
```
timeit: 71.4 µs ± 796 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

My code:
```
​def palindrome(string):
    """Check if input string (all lower-case characters) is a palindrome."""
    return (string == string[::-1])
    
assert palindrome('') == True
assert palindrome('a') == True
assert palindrome('ab') == False
assert palindrome('abba') == True
assert palindrome('redivider') == True
print('All passed!')
```
timeit: 68.6 µs ± 900 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Very minute difference but its also a very minute function. Over time, and with much bigger functions, this difference would become more prevalent.

**Comment by gudnm** [comment]
Thank you! Good point and very Pythonic. I only decided to go with the longer version as it's somewhat language agnostic and to me this was more of an exercise in algorithms rather than Python and its idioms.
